In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns
import joblib
from sklearn.preprocessing import StandardScaler

In [41]:
df = pd.read_csv('processed_kaggle.csv')
df

,id,weight,ap_hi,ap_lo,cholesterol,gluc,active,age_years,BMI,BMI_category,pulse_pressure
0,26681,59.5,120,85,1,1,1,53.112329,24.765869,2,35
1,58585,59.0,130,90,1,1,1,57.756164,23.046875,2,40
2,54339,88.0,120,80,2,1,1,41.449315,28.734694,3,40
3,17273,62.0,120,90,1,1,1,51.465753,19.789971,2,30
4,25420,81.0,120,80,1,1,1,49.783562,29.043709,3,40
...,...,...,...,...,...,...,...,...,...,...,...
13995,34457,88.0,160,100,1,3,1,57.780822,31.934969,4,60
13996,40980,105.0,140,90,1,1,1,61.484932,33.897211,4,50
13997,83726,87.0,160,1100,1,1,1,59.920548,34.413196,4,-940
13998,11086,73.0,120,80,1,1,1,50.164384,26.813590,3,40
13999,26267,87.0,140,90,1,1,1,57.780822,32.744928,4,50

In [43]:
reserve_id = df['id']
df_classify = df.drop(columns=['id'])
reserve_id

0        26681
1        58585
2        54339
3        17273
4        25420
         ...
13995    34457
13996    40980
13997    83726
13998    11086
13999    26267
Name: id, Length: 14000, dtype: int64

In [44]:
df_classify

,weight,ap_hi,ap_lo,cholesterol,gluc,active,age_years,BMI,BMI_category,pulse_pressure
0,59.5,120,85,1,1,1,53.112329,24.765869,2,35
1,59.0,130,90,1,1,1,57.756164,23.046875,2,40
2,88.0,120,80,2,1,1,41.449315,28.734694,3,40
3,62.0,120,90,1,1,1,51.465753,19.789971,2,30
4,81.0,120,80,1,1,1,49.783562,29.043709,3,40
...,...,...,...,...,...,...,...,...,...,...
13995,88.0,160,100,1,3,1,57.780822,31.934969,4,60
13996,105.0,140,90,1,1,1,61.484932,33.897211,4,50
13997,87.0,160,1100,1,1,1,59.920548,34.413196,4,-940
13998,73.0,120,80,1,1,1,50.164384,26.813590,3,40
13999,87.0,140,90,1,1,1,57.780822,32.744928,4,50

In [45]:
scaler = joblib.load('scaler.pkl')
normalize_columns = ['weight', 'ap_hi', 'ap_lo', 'age_years', 'BMI', 'pulse_pressure']

X_predict[normalize_columns] = scaler.transform(df_classify[normalize_columns])

In [46]:
X_predict

,weight,ap_hi,ap_lo,cholesterol,gluc,active,age_years,BMI,BMI_category,pulse_pressure
0,-1.089900,-0.374532,0.462750,1,1,1,-0.024983,-0.498537,2,-0.919552
1,-1.130329,0.289920,1.028756,1,1,1,0.663350,-0.872321,2,-0.446753
2,1.214571,-0.374532,-0.103256,2,1,1,-1.753734,0.364459,3,-0.446753
3,-0.887753,-0.374532,1.028756,1,1,1,-0.269047,-1.580514,2,-1.392352
4,0.648561,-0.374532,-0.103256,1,1,1,-0.518390,0.431652,3,-0.446753
...,...,...,...,...,...,...,...,...,...,...
13995,1.214571,2.283276,2.160768,1,3,1,0.667005,1.060338,4,1.444444
13996,2.589168,0.954372,1.028756,1,1,1,1.216047,1.487015,4,0.498845
13997,1.133712,2.283276,115.361940,1,1,1,0.984166,1.599212,4,-93.115394
13998,0.001692,-0.374532,-0.103256,1,1,1,-0.461942,-0.053273,3,-0.446753
13999,1.133712,0.954372,1.028756,1,1,1,0.667005,1.236458,4,0.498845

In [58]:
# Load the model
loaded_mlp_model = joblib.load('mlp_model.pkl')

# ใช้โมเดลที่โหลดไว้ทำนายผล
predictions = loaded_mlp_model.predict(X_predict)
predictions_df = pd.DataFrame(predictions)

#join the predictions with the reserve_id
predictions_df['id'] = reserve_id
predictions_df['cardio'] = predictions_df[0]
predictions_df.drop(columns=[0], inplace=True)
predictions_df

#No: 0 , Yes: 1
predictions_df['cardio'] = predictions_df['cardio'].apply(lambda x: 'Yes' if x == 1 else 'No')

# Save the predictions to a CSV file
predictions_df.to_csv('predictions.csv', index=False)